---
apiVersion: v1
kind: Namespace
metadata:
  name: containers

---
apiVersion: v1
kind: Namespace
metadata:
  name: cj

---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: containers
  labels:
    app: multi-container-app
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html


  - name: busybox-1
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello from busy' > /usr/share/nginx/html/index.html && sleep 5"]
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html


  - name: busybox-2
    image: busybox
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html

  volumes:
  - name: shared-volume
    emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: containers
spec:
  selector:
    app: multi-container-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-curler
  namespace: cj
spec:
  schedule: "*/1 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: curlimages/curl:latest
            command: ["curl", "http://nginx-service.containers.svc.cluster.local/"]
          restartPolicy: OnFailure
